### ISSUE TITLE
mongodb 数据

### ISSUE THREAD

**Issue by nonocast** [nonocast/me#102]
```sh
~ ps ax | grep mongod
 1434   ??  S      3:20.88 /usr/local/opt/mongodb/bin/mongod --config /usr/local/etc/mongod.conf
```
从中可以看到mongod和配置文件路径。

从mongod.conf可以追到数据文件目录，

```yaml
systemLog:
  destination: file
  path: /usr/local/var/log/mongodb/mongo.log
  logAppend: true
storage:
  dbPath: /usr/local/var/mongodb
net:
  bindIp: 127.0.0.1
```
