### ISSUE TITLE
mongodb 安装一般方法

### ISSUE THREAD

**Issue by nonocast** [nonocast/me#110]
## 基本步骤

- 官网下载mongodb安装包，将包内bin内的可执行文件(mongo, mongod, mongos)复制(cp)或链接(link)到/usr/local/bin，然后就可以通过shell手动启动mongo
- 如果需要做成系统服务，则需要根据操作系统的launcher进行相应配置

## 以macOS为例

1. 在[MongoDB Community Download | MongoDB](https://www.mongodb.com/try/download/community)页面中得到4.4.1的下载地址https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.4.1.tgz
2. wget到本地，cp bin/*到/usr/local/bin
3. 预设一个配置文件/usr/local/etc/mongo.conf
```yml
storage:
  dbPath: /usr/local/var/mongodb
  journal:
    enabled: true

systemLog:
  destination: file
  logAppend: true
  path: /usr/local/var/log/mongodb/mongod.log

net:
  port: 27017
  bindIp: 0.0.0.0
```
4. 新建服务启动配置 /Library/LaunchDaemons/org.mongodb.mongod.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN""http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>org.mongodb.mongod</string>
        <key>ProgramArguments</key>
        <array>
            <string>/usr/local/bin/mongod</string>
            <string>run</string>
            <string>--config</string>
            <string>/usr/local/etc/mongod.conf</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
    </dict>
</plist>
```

```sh
~ sudo launchctl load /Library/LaunchDaemons/org.mongodb.mongod.plist
~ sudo launchctl start org.mongodb.mongod.list
~ sudo launchctl list | grep mongod
```

注:
1. Launch Daemon: 在开机时加载(load), Launch Agent: 在使用者登录时加载
2. launchctl和pm2一样区分用户的，所以sudo launchctl和launchctl得到的服务是不一样的，需要将mongod置于系统服务中
