### ISSUE TITLE
Docker 学习 (Part 4 - Traefik)

### ISSUE THREAD

**Issue by nonocast** [nonocast/me#183]
根据官网[Quick Start - Traefik](https://doc.traefik.io/traefik/getting-started/quick-start/)，通过如下docker-compose.yml可以直接运行Traefik,

```yml
version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
```

注：
- 如果需要将traefik映射本地的其他端口，只需要修改ports中"9999:80"
- 可以通过http://localhost:8080打开dashboard
- traefik自身的配置可以通过配置文件(traefik.yml), command和env 3中方式，简单的话就是command, 复杂的话就用traefik.yml: `docker run -d -p 8080:8080 -p 80:80 \
    -v $PWD/traefik.yml:/etc/traefik/traefik.yml traefik:v2.5`

此时你加入一下你的backend service，

```yml
  backend:
    image: registry.cn-shanghai.aliyuncs.com/h705c/demo-backend:latest
```

注:
- backend的服务是开在端口9000上
- 通过dashboard可以查看内建的routers，你会发现4个Rules, 其中Host('backend-local')是可以直接访问backend service，即`curl -H Host:backend-lcoal localhost`，等同于直接访问backend:9000，挺妖的

我们来尝试把backend挂载到/backend下，

```yml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: registry.cn-shanghai.aliyuncs.com/h705c/demo-backend:latest
    labels:
      - 'traefik.http.routers.backend.rule=PathPrefix(`/backend`)'
      - 'traefik.http.routers.backend.middlewares=backend-stripprefix'
      - 'traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/backend'
      - 'traefik.http.middlewares.backend-stripprefix.stripprefix.forceSlash=false'
      - 'traefik.http.services.backend.loadbalancer.server.port=9000'

  frontend:
    image: registry.cn-shanghai.aliyuncs.com/h705c/demo-frontend:latest
    labels:
      - 'traefik.http.routers.frontend.rule=PathPrefix(`/`)'
 ```

注:
- 我们需要将/backend映射到backend容器的/
- 第一步: 通过PathPrefix进行路径的匹配
- 第二步: 通过StripPrefix的middleware去掉/backend然后传递给backend容器
- 这个比nginx会清晰很多，nginx你懂的

参考阅读:
- [StripPrefix - Traefik | Site | v2.0](https://doc.traefik.io/traefik/v2.0/middlewares/stripprefix/)
- [Traefik v1 to v2 - Traefik](https://doc.traefik.io/traefik/migration/v1-to-v2/)
