### ISSUE TITLE
学习 three.js (Part 3: react-three-fiber)

### ISSUE THREAD

**Issue by nonocast** [nonocast/me#326]
ref: [pmndrs/react-three-fiber: 🇨🇭 A React renderer for Three.js](https://github.com/pmndrs/react-three-fiber)
通过r3f可以通过tag的方式来写threejs

1. `yarn create vite`project name: hello
2. `yarn add three @react-three/fiber`
3. `yarn dev`

App.jsx
```jsx
import { Canvas } from '@react-three/fiber'
import './App.css'

function App() {
  return (
    <>
      <div className="canvas-container">
        <Canvas camera={{ position: [5, 3, 5], fov: 75 }}>
          <ambientLight intensity={0.5} />
          <directionalLight position={[0, 5, 5]} />
          <mesh>
            <boxGeometry args={[2, 2, 2]} />
            <meshStandardMaterial color="red" />
          </mesh>
        </Canvas>
      </div>
    </>
  );
}

export default App
```

App.css
```css
.canvas-container {
  width: 100vw;
  height: 100vh;
  position: relative;
  overflow: hidden;
}

.canvas-container canvas {
  display: block;
}
```

<img width="1148" alt="Screenshot 2024-09-11 at 23 26 10" src="https://github.com/user-attachments/assets/4e4603c4-20b5-4906-9d49-402317f63132">

增加orbit control,
```jsx
import { Stats, OrbitControls } from '@react-three/drei'

<Canvas camera={{ position: [5, 3, 5], fov: 75 }}>
  ...
  <OrbitControls />
  <Stats />
</Canvas>
```
