### ISSUE TITLE
学习 Live2D (Part 3.1: 从零构建Native)

### ISSUE THREAD

**Issue by nonocast** [nonocast/me#349]
`本文环境: Mac mini 2024 M4, MacOS Sequoia 15.5, Xcode 16.3`

我会分2个issue来说明剥离过程，本文使用LAppDelegate的glfw windows方式，后面我们再来看怎么去掉glfw直接通过NSView来做。

项目结构规划
```
Live2DApp/
├── Live2D/
│   ├── App/                   # 样例运行逻辑（来自 Samples/OpenGL）
│   │   ├── LAppDelegate.hpp/cpp
│   │   ├── LAppLive2DManager.hpp/cpp
│   │   ├── LAppModel.hpp/cpp
│   │   ├── LAppView.hpp/cpp
│   │   ├── LAppPal.hpp/cpp
│   │   └── LAppDefine.hpp
│
│   ├── Core/                  # Cubism Core SDK
│   │   ├── live2dcubismcore.hpp
│   │   ├── live2dcubismcore.framework 或 .a
│   │   └── ...
│
│   ├── Framework/             # Cubism Framework SDK
│   │   ├── math/
│   │   ├── model/
│   │   ├── rendering/
│   │   ├── type/
│   │   └── ...
│
│   └── ThirdParty/            # 第三方依赖的Header
│       ├── glfw/include
│       ├── glew/include
│       └── stb/include
│
├── main.mm                    # 应用入口（直接运行 LAppDelegate）
└── Live2DApp.xcodeproj/
```
Models的目录结构放在~/Documents/Live2DApp
```
~/Documents/Live2DApp/
├── Models/
│   ├── Haru/
│   ├── Hiyori/
│   ├── Mao/
│   ├── Mark/
│   ├── Natori/
│   ├── Rice/
│   └── Wanko/
│
├── Shaders/ (Sample中Standard对应桌面平台，StandardES对应移动端)
│   ├── FragSprite.frag       ← 桌面平台片段着色器 
│   └── VertSprite.vert       ← 桌面平台顶点着色器
│
├── close.png                 ← 关闭按钮图标
├── icon_gear.png             ← 齿轮图标（设置按钮）
└── back_class_normal.png     ← 背景图
```

这里把Models放在外面有几个原因:
1. 程序和内容分开有好处，这样可以在安装后维护Models目录
2. 程序最终打包出来的是.app, 在.app/Resources中保留目录结构是件特别麻烦的事情，放在外面可以简化很多事情

## Step 1: Skeleton

这里我们用xcodegen来创建项目，用Xcode也是一样的。

```sh
mkdir hello-live2d-mac && cd hello-live2d-mac
touch main.mm project.yml
```

main.mm
```mm
#import <Foundation/Foundation.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSLog(@"Hello, World!");
    }
    return 0;
}
```

project.yml
```yml
name: Live2DApp
targets:
  Live2DApp:
    type: tool
    platform: macOS
    sources: ['.']
    exclude: ['.git']
    settings:
      base:
        CLANG_CXX_LANGUAGE_STANDARD: "c++17"
        CLANG_ENABLE_OBJC_ARC: YES
```

然后通过xcodegen来生成xcodeproj
```sh
❯ xcodegen
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/nonocast/Develop/live2d/hello-live2d-mac/Live2DApp.xcodeproj
❯ xcodebuild -configuration Debug SYMROOT=build
... 省略
** BUILD SUCCEEDED **

❯ ./build/Debug/Live2DApp
2025-06-01 14:27:52.684 Live2DApp[1408:15944053] Hello, World!
```

## Step 2: 搬家

把SDK中对应代码复制到目标Live2D/下面

project.yml
```yml
name: Live2DApp
options:
  bundleIdPrefix: cn.nonocast
  deploymentTarget:
    macOS: "10.15"

configs:
  Debug:
    buildSettings:
      ENABLE_HARDENED_RUNTIME: YES
  Release:
    buildSettings:
      ENABLE_HARDENED_RUNTIME: YES

targets:
  Live2DApp:
    type: application
    platform: macOS
    deploymentTarget: "10.15"
    info:
      path: Info.plist
    sources:
      - path: main.mm
      - path: Live2D
    settings:
      base:
        HEADER_SEARCH_PATHS:
          - $(SRCROOT)/Live2D/App/**
          - $(SRCROOT)/Live2D/Core/**
          - $(SRCROOT)/Live2D/Framework/**
          - $(SRCROOT)/Live2D/ThirdParty/glfw/include
          - $(SRCROOT)/Live2D/ThirdParty/glew/include
          - $(SRCROOT)/Live2D/ThirdParty/stb/include
        LIBRARY_SEARCH_PATHS:
          - $(SRCROOT)/Live2D/Core
        OTHER_LDFLAGS:
          -lc++
          -llive2dcubismcore
          -lGLEW
          -lglfw3
          -framework OpenGL
          -framework CoreGraphics
          -framework CoreVideo
          -framework IOKit
          -framework AppKit
        GCC_PREPROCESSOR_DEFINITIONS:
          - CSM_TARGET_MAC_GL=1
        CLANG_CXX_LANGUAGE_STANDARD: c++17
        CLANG_CXX_LIBRARY: libc++
```

Info.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
</dict>
</plist>
```

Makefile
```make
PROJECT = Live2DApp
SCHEME = Live2DApp
CONFIG = Debug
SYMROOT = build
APP_PATH = $(SYMROOT)/$(CONFIG)/$(PROJECT).app
APP_EXEC = $(APP_PATH)/Contents/MacOS/$(PROJECT)

.PHONY: all xcodeproj build run clean

all: build

xcodeproj:
	@echo "📦 Generating Xcode project with XcodeGen..."
	xcodegen

build: xcodeproj
	@echo "🔨 Building $(PROJECT)..."
	xcodebuild -project $(PROJECT).xcodeproj -scheme $(SCHEME) -configuration $(CONFIG) SYMROOT=$(SYMROOT)

run: build
	@echo "🚀 Running..."
	@$(APP_EXEC)

clean:
	@echo "🧹 Cleaning build artifacts..."
	rm -rf $(SYMROOT)
	rm -rf $(PROJECT).xcodeproj
```

搞定以后就可以build了
```sh
❯ make run
📦 Generating Xcode project with XcodeGen...
xcodegen
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/nonocast/Develop/live2d/hello-live2d-mac/Live2DApp.xcodeproj
🔨 Building Live2DApp...
xcodebuild -project Live2DApp.xcodeproj -scheme Live2DApp -configuration Debug SYMROOT=build
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project Live2DApp.xcodeproj -scheme Live2DApp -configuration Debug SYMROOT=build

Build settings from command line:
    SYMROOT = build

... 省略 ...

/System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -f -R -trusted /Users/nonocast/Develop/live2d/hello-live2d-mac/build/Debug/Live2DApp.app

** BUILD SUCCEEDED **

🚀 Running...
2025-06-01 16:01:24.734 Live2DApp[6364:16022440] hello world.
```

修改main.mm
```mm
#import <Foundation/Foundation.h>
#import "LAppDelegate.hpp"

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSLog(@"hello world.");
        
        LAppDelegate::GetInstance()->Initialize();
        LAppDelegate::GetInstance()->Run();
    }
    return 0;
}
```

直接make run以后就能看到如下界面

<img src="https://github.com/user-attachments/assets/2f753824-7cdb-4396-9d57-bf01372861df" />

## 补充

1. 关于Xcode
我在写issue之前都是用的Xcode，无非就是设置Header Search Paths, Library Search Paths, Linker Flags，这些通过ChatGPT都能回答，就不展开了，总之想说xcodegen/xcodebuild是和Xcode操作是完全对等的
2. thirdparty
直接通过CMake编译，编译后拿到lib复制到Core/下面，对应Core下面的libGLEW.a, libglfw3.a

编译步骤如下:
```sh
❯ pwd
/Users/nonocast/Desktop/thirdp/CubismSdkForNative-5-r.3/Samples/OpenGL/thirdParty
❯ ls
scripts stb
❯ ./scripts/setup_glew_glfw
- Setup GLEW 2.2.0
Downloading...
Extracting...
- Setup GLFW 3.4
Downloading...
Extracting...
❯ cd glew
❯ ls
LICENSE.txt README.md   bin         config      glew.pc.in  lib
Makefile    auto        build       doc         include     src
❯ make
cc -DGLEW_NO_GLU -DGLEW_BUILD -Os -Wall -W -Iinclude -dynamic -fno-common -pedantic -fPIC -std=c89  -o tmp/darwin/default/shared/glew.o -c src/glew.c
❯ file lib/libGLEW.a
lib/libGLEW.a: current ar archive random library
// 这样就得到了libGLEW.a
❯ cd ../glfw
❯ cmake -S . -B build
-- The C compiler identification is AppleClang 17.0.0.17000013
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Including Cocoa support
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Documentation generation requires Doxygen 1.9.8 or later
-- Configuring done (0.7s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/nonocast/Desktop/thirdp/CubismSdkForNative-5-r.3/Samples/OpenGL/thirdParty/glfw/build
❯ cmake --build build
[  1%] Building C object src/CMakeFiles/glfw.dir/context.c.o
[  2%] Building C object src/CMakeFiles/glfw.dir/init.c.o
[  3%] Building C object src/CMakeFiles/glfw.dir/input.c.o
... 省略
[ 98%] Building C object tests/CMakeFiles/window.dir/window.c.o
[100%] Linking C executable window.app/Contents/MacOS/window
[100%] Built target window
❯ file build/src/libglfw3.a
build/src/libglfw3.a: current ar archive random library
// 这样就得到了libglfw3.a
```

3. 编译LAppDelegate会发生GLtypes.h included before glew.h Typedef redefinition ('unsigned int' vs 'void *'), 需要去掉.hpp中glew.h和glfw3.h的include，改为手动声明struct GLFWwindow 
```h
#include <string>
//#include <GL/glew.h>
//#include <GLFW/glfw3.h>
#include "Type/csmVector.hpp"
#include "LAppAllocator.hpp"

class LAppView;
class LAppTextureManager;
struct GLFWwindow;
```

4. 加载路径问题
要正确显示所有元素，必须正确匹配model, shaders, back所有路径，默认在加载模型的路径是：

```cpp
// LAppLive2DManager.cpp SetUpModel()
csmString crawlPath(LAppDelegate::GetInstance()->GetExecuteAbsolutePath().c_str());
crawlPath += ResourcesPath;

// LAppDelegate.hpp
void LAppDelegate::SetExecuteAbsolutePath()
{
    char path[1024];
    uint32_t size = sizeof(path);
    _NSGetExecutablePath(path, &size);
    this->_executeAbsolutePath = dirname(path);
    this->_executeAbsolutePath += "/";
}
```
所以，最简单的该法就是将LAppDelegate的AbsolutePath从_NSGetExecutablePath改为'~/Documents/Live2DApp'

对应的代码: https://github.com/nonocast/hello-live2d-mac, tag: glfw
也可以直接下载代码: https://github.com/nonocast/hello-live2d-mac/releases/tag/glfw
