### ISSUE TITLE
elasticsearch 实践

### ISSUE THREAD

**Issue by nonocast** [nonocast/me#95]
刚接触elasticsearch还是比较懵*的，和传统的数据库玩法，包括ELK的组合确实比较繁杂。

elasticsearch本身就是独立的搜索服务，可以通过docker直接拉起来，
`docker run -d --name="elasticsearch" -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.8.1`

elasticsearch所有的操作都是通过http restful api实现，有3个操作方式：
- Chrome plugin: [ElasticSearch Head](https://chrome.google.com/webstore/detail/elasticsearch-head/ffmkiejjmecolpfloofpjologoblkegm)
- curl
- Kibana DevTools

最推荐的是Kibana DevTools，带自动联想，输出json支持也支持fold，所以本地拉一个Kibana

`docker run -d --name="kibana" --link elasticsearch -p 5601:5601 docker.elastic.co/kibana/kibana:7.8.1`

然后理解一下几个概念：
- es中所说的index, 就好比是传统数据的table或者mongodb中的collection (原本index是对应database, 然后type对应table/collection，7.0后去掉了type，只是保留了默认的_doc，等于说去掉一个级别的目录)
- index是document的集合，document就是json
- index是非常轻量级的，比如log-20200901, log-20200902，都是按天，搜索的时候log*就可以跨index搜索，这个在常规数据库是做不到的
- index是有mapping的，es会动态生成，同时也支持手动指定

## 体验一下搜索

es比mysql, mongodb最大的差异就是采用倒排索引，所以极大的提升了搜索性能，直接follow下面的链接体验一下，

- [medcl/elasticsearch-analysis-ik: The IK Analysis plugin integrates Lucene IK analyzer into elasticsearch, support customized dictionary.](elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.8.1/elasticsearch-analysis-ik-7.8.1.zip)

- `docker exec -it elasticsearch bash`安装ik，然后`dcoker restart elasticsearch`重启服务
- 示例中的index可以改为任意名字，比如foo之类
- 通过Kibana的Dev Tools很容易体验效果

## 应用程序日志收集和分析

filebeat将程序日志采集后推送到es进行存储和分析。

比如我们将程序的日志分为2个类型：
- 应用 (app-%date.log)
- 访问 (access-%date.log)

那么filebeat就可以配置3个inputs,

```yml
- type: log
  paths:
    - /var/log/create-webapp/app*.log
  fields:
    type: create-webapp-app
  json.keys_under_root: true
  json.overwrite_keys: true
  json.message_key: message
  json.add_error_key: true

- type: log
  paths:
    - /var/log/create-webapp/access*.log
  fields:
    type: create-webapp-access
  json.keys_under_root: true
  json.overwrite_keys: true
  json.message_key: message
  json.add_error_key: true
```

然后对应的filebeat.yml

```yml
filebeat.config.inputs:
  enabled: true
  path: inputs.d/*.yml

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]
  #index: "logs-%{[beat.version]}-%{+yyyy.MM.dd}"
  indices:
    - index: "logs-create-webapp-app-%{+yyyy.MM.dd}"
      when.equals:
        fields.type: create-webapp-app
    - index: "logs-create-webapp-access-%{+yyyy.MM.dd}"
      when.equals:
        fields.type: create-webapp-access
```

这样就在es上形成2个index线，分别是logs-create-webapp-app-%{+yyyy.MM.dd}和logs-create-webapp-access-%{+yyyy.MM.dd}。

现在就可以通过Kibana中的Discover或者Log查看日志 (index: logs-create-webapp*), 如果在DevTools就可以通过`GET /logs-create-webapp*/_search`进行搜索。

如果应用需要对接es就可以通过[elastic/elasticsearch-js](https://github.com/elastic/elasticsearch-js)

查询数据，

```js
const _ = require('lodash');
const debug = require('debug')('app');
const { Client } = require('@elastic/elasticsearch')

run();

async function run() {
  const client = new Client({ node: 'http://localhost:9200' })

  let { body } = await client.search({
    index: 'logs-create-webapp*',
    size: 100
  });
  console.log(body);
  console.log(_.map(body.hits.hits, x => x._source.message));
}
```

现在我们在koa-logger中记录了所有restful api的访问记录，

```js
let level = err || status >= 400 ? 'warn' : 'info';
let message = `${ctx.method} ${ctx.originalUrl} ${status} ${time(start)} ${length ? bytes(length).toLowerCase() : '-'}`;
accessLogger.log(level, message, {
  route: `${ctx.method} ${ctx.path}`,
  req: {
    ip: ctx.ip,
    userAgent: ctx.userAgent.source,
    method: ctx.method,
    path: ctx.path,
    originalUrl: ctx.originalUrl,
  },
  res: {
    status,
    time: Date.now() - start,
    length
  }
});
```

logger采用winston，所以应用日志和访问日志需要对应不同的logger， 记录到不同的文件中。

这个时候就可以group route查看每个api访问的次数

```js
let { body } = await client.search({
  index: 'logs-create-webapp-access*',
  body: {
    size: 0,
    aggs: {
      routes: {
        terms: {
          field: 'route.keyword'
        }
      }
    }
  }
});

console.log(body.aggregations.routes.buckets);
```

输出如下：
```
[
  { key: 'GET /api/v1/', doc_count: 28 },
  { key: 'GET /api/v1/test', doc_count: 12 },
  { key: 'GET /api/v1/oauth/authorize', doc_count: 1 }
]
```
